package es.cifpcm.miali.model;
// Generated 18-dic-2018 11:53:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="mialidb"
)
public class Customer  implements java.io.Serializable {


     private Short customerId;
     private String firstName;
     private String lastName;
     private String telefono;
     private String email;
     private Date fechaDeNacimiento;

    public Customer() {
    }

	
    public Customer(String firstName, String lastName, String telefono, Date fechaDeNacimiento) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.telefono = telefono;
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public Customer(String firstName, String lastName, String telefono, String email, Date fechaDeNacimiento) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.telefono = telefono;
       this.email = email;
       this.fechaDeNacimiento = fechaDeNacimiento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Short getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_de_nacimiento", nullable=false, length=10)
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }




}


