package es.cifpcm.miali.model;
// Generated 18-dic-2018 11:53:24 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productoffer generated by hbm2java
 */
@Entity
@Table(name="productoffer"
    ,catalog="mialidb"
)
public class Productoffer  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private Float productPrice;
     private String productPicture;
     private int idMunicipio;
     private int productStock;

    public Productoffer() {
    }

	
    public Productoffer(String productName, int idMunicipio, int productStock) {
        this.productName = productName;
        this.idMunicipio = idMunicipio;
        this.productStock = productStock;
    }
    public Productoffer(String productName, Float productPrice, String productPicture, int idMunicipio, int productStock) {
       this.productName = productName;
       this.productPrice = productPrice;
       this.productPicture = productPicture;
       this.idMunicipio = idMunicipio;
       this.productStock = productStock;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    
    @Column(name="product_name", nullable=false, length=512)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="product_price", precision=12, scale=0)
    public Float getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(Float productPrice) {
        this.productPrice = productPrice;
    }

    
    @Column(name="product_picture", length=512)
    public String getProductPicture() {
        return this.productPicture;
    }
    
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture;
    }

    
    @Column(name="id_municipio", nullable=false)
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    
    @Column(name="product_stock", nullable=false)
    public int getProductStock() {
        return this.productStock;
    }
    
    public void setProductStock(int productStock) {
        this.productStock = productStock;
    }




}


