package es.cifpcm.miali.model;
// Generated 18-dic-2018 11:53:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincias generated by hbm2java
 */
@Entity
@Table(name="provincias"
    ,catalog="mialidb"
)
public class Provincias  implements java.io.Serializable {


     private short idProvincia;
     private String nombre;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Provincias() {
    }

	
    public Provincias(short idProvincia, String nombre) {
        this.idProvincia = idProvincia;
        this.nombre = nombre;
    }
    public Provincias(short idProvincia, String nombre, Set<Municipios> municipioses) {
       this.idProvincia = idProvincia;
       this.nombre = nombre;
       this.municipioses = municipioses;
    }
   
     @Id 

    
    @Column(name="id_provincia", unique=true, nullable=false)
    public short getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(short idProvincia) {
        this.idProvincia = idProvincia;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincias")
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }




}


