//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscosRamirezFranzJosue.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class Cliente
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {
      this.Puntuacions = new HashSet<Puntuacion>();
    }

    public int id { get; set; }
    [Required]    
    public string Nombre { get; set; }
    [Required(ErrorMessage = "La dirección de Email es requerida")]
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public Nullable<System.DateTime> FechaNacimiento { get; set; }
    public Nullable<System.DateTime> FechaRegistro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Puntuacion> Puntuacions { get; set; }
  }
}
